[package]
name = "mal-js-detection"
version = "0.1.0"
edition = "2024"

[dependencies]
async-std = "1.13.1"
clap = { version = "4.5.32", features = ["derive"] }
dockers = "=0.1.6"
env_logger = "0.11.7"
futures = "0.3.31"
log = "0.4.27"
oxc = {version = "0.61.2", features = ["ast_visit", "serialize"]}
regex = "1.11.1"
reqwest = "0.12.15"
serde = "1.0.219"
serde_json = "1.0.140"

