services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - ${RABBITMQ_CONNECTION_PORT}:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_CONNECTION_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_CONNECTION_PASSWORD}
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
  sandbox:
    build:
      context: .
      dockerfile: ./docker/sandbox_Dockerfile
    image: js-sandbox
    container_name: js-sandbox-av
    volumes:
      - ./sandbox/consumer/main.py:/sandbox/consumer/main.py
      - ${CONFIG_FOLDER}:/sandbox/config/
    cap_add:
      - NET_ADMIN # this capability is needed in case we want to block outgoing TCP traffic

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."  

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
