host:
  host: 127.0.0.1
  docker: rabbitmq
  host_port: 5672
  docker_port: 5672
queues:
  core_files_queue:
    name: malsmug.files_for_analysis
    durable: true
    auto_delete: true
  sandbox_iocs_queue:
    name: malsmug.analysis_iocs
    durable: true
    auto_delete: true
exchanges:
  main_exchange:
    name: malsmug.analysis